export const GLOBALTYPES = {
  AUTH: "AUTH",
  RESPONSEMESSAGE: "RESPONSEMESSAGE",
  MODEL_POST: "MODEL_POST",
  SOCKET: "SOCKET",
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
};

export const PROFILE_TYPES = {
  LOADING: "LOADING_PROFILE",
  GET_USER: "GET_USER_PROFILE",
  GET_ID: "GET_ID_PROFILE",
  FOLLOW: "FOLLOW",
  UNFOLLOW: "UNFOLLOW",
  GET_POSTS_PROFILE: "GET_POSTS_PROFILE",
  GET_MORE_POST: "GET_MORE_POST",
};

export const POST_TYPES = {
  LOADING_POST: "LOADING_POST",
  CREATE_POST: "CREATE_POST",
  GET_POSTS: "GET_POSTS",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  LIKE_POST: "LIKE_POST",
  UNLIKED_POST: "UNLIKED_POST",
  COMMENT_POST: "COMMENT_POST",
  EDIT_COMMENT: "EDIT_COMMENT",
  LIKE_COMMENT: "LIKE_COMMENT",
  UNLIKE_COMMENT: "UNLIKE_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
  GET_DETAILS_POST: "GET_DETAILS_POST",
  GET_MORE_POST: "GET_MORE_POST",
};

export const EXPLORE_TYPES = {
  LOADING_EXPLORE: "LOADING_EXPLORE",
  EXPLORE_POSTS: "EXPLORE_POSTS",
  GET_MORE_POST: "GET_MORE_POST",
};
export const SUGGESTION_USER_TYPES = {
  LOADING_SUGGESTION: "LOADING_SUGGESTION",
  GET_USER_SUGGESTION: "GET_USER_SUGGESTION",
};

export const NOTIFICATIONS_TYPES = {
  LOADING_NOTIFICATIONS: "LOADING_NOTIFICATIONS",
  CREATE_NOTIFICATION: "CREATE_NOTIFICATION",
  GET_NOTIFICATIONS: "GET_NOTIFICATIONS",
  DELETE_NOTIFICATION: "DELETE_NOTIFICATION",
  DELETE_ALL_NOTIFICATION: "DELETE_ALL_NOTIFICATION",
  IS_READ: "IS_READ",
  SOUND: "SOUND",
};

export const CHATS_TYPES = {
  OPEN_CHAT_USER: "OPEN_CHAT_USER",
  SEND_MESSAGE: "SEND_MESSAGE",
  GET_MESSAGES: "GET_MESSAGES",
  LOADE_MORE_MESSAGES: "LOADE_MORE_MESSAGES",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  GET_CHATS: "GET_CHATS",
  DELETE_CHAT: "DELETE_CHAT",
  CHECK_ONLINE_OFFLINE: "CHECK_ONLINE_OFFLINE",
};
